---
title: "HW1"
author: "Guangyu Qiu"
date: "2026-09-14"
output: pdf_document
---
## At first glance, we can see that the ball will end up in the hands of the last person who first touched it. Since everyone is sitting around a round table, my guess is that the person sitting opposite the host is the most likely to end up holding the ball (given p = 0.5).

```{r setup}
set.seed(648)
library(dplyr)
```


```{r question1}
# AI disclosure: this code was mostly hand-coded by me. The only help I received from AI was that, at first, I used 'j' instead of 'i' inside the loop and did not set 'i <- j' after the loop ended. I have now revised the code to use 'i consistently throughout.

# say p is probability for heads, which mean left
present_party <- function(chair = 10, p = 0.5){
  x <- rep(0, chair)
  i <- 1 # the host hold the ball at the beginning
  x[i] <- 1
  n <- 0
  while (sum(x) != chair){
    a <- 2 * rbinom(1, 1, p) - 1 # if head, pass to left, then 1, otherwise -1
    i <- i + a
    if (i == 0) i <- chair else if (i == chair + 1) i <- 1
    x[i] <- 1
    n <- n + 1
  }
  return(c(i,n))
}

present_party()
```

```{r question2} 
# To prove it is correct, we should consider some extreme cases:
present_party(chair = 10, p = 1) # would return 10 and 9 rounds
present_party(chair = 10, p = 0) # would return 2 and 9 rounds
present_party(chair = 1, p = 0.5) # would return 1 and 0 rounds
```
```{r question3}
sim <- rep(0,10000)
for (j in seq_along(sim)){
  sim[j] <- present_party()
}

```

