---
title: "Lab04"
author: "Guangyu Qiu"
date: "2026-09-17"
output: pdf_document
---
# Part 1 Question 1: Using MC to simulate pi
```{r}
# original code
pv <- profvis::profvis({
  simulate_pi <- function(n = 5e6) {
    inside <- 0
    for (i in 1:n) {
      x <- runif(1, -1, 1)
      y <- runif(1, -1, 1)
      if (x^2 + y^2 <= 1) inside <- inside + 1
    }
    4 * inside / n
  }
  
  set.seed(1)
  simulate_pi(5e6)
})
htmlwidgets::saveWidget(pv, "simulatepi.html")
```

```{r}
# my attempt
pv2 <- profvis::profvis({
  simulate_pi2 <- function(n = 5e6) {
    inside <- 0
    x <- runif(n, -1, 1)
    y <- runif(n, -1, 1)
    inside <- (x^2 + y^2 <= 1) # now it should become 0/1, with 5e6 length
    4 * sum(inside) / n
  }
  
  set.seed(1)
  simulate_pi2(5e6)
})
htmlwidgets::saveWidget(pv2, "simulatepi_mytry.html")
```
```{r}
# Prof's attempt
pv3 <- profvis::profvis({
  simulate_pi3 <- function(n = 5e6) {
    points <- runif(n * 2, -1, 1) |>
      matrix(ncol = 2)
    mean(rowSums(points^2) <= 1) *4
  }
  set.seed(1)
  simulate_pi3(5e6)
})
htmlwidgets::saveWidget(pv3, "simulatepi_prof.html")
```


```{r}
bench::mark(
  method1 = {simulate_pi <- function(n = 5e6) {
    inside <- 0
    for (i in 1:n) {
      x <- runif(1, -1, 1)
      y <- runif(1, -1, 1)
      if (x^2 + y^2 <= 1) inside <- inside + 1
    }
    4 * inside / n
  }
  
  set.seed(1)
  simulate_pi(5e6)},
  method2 = {simulate_pi <- function(n = 5e6) {
    inside <- 0
    x <- runif(n, -1, 1)
    y <- runif(n, -1, 1)
    inside <- (x^2 + y^2 <= 1) # now it should become 0/1, with 5e6 length
    4 * sum(inside) / n
  }
  
  set.seed(1)
  simulate_pi(5e6)},
  relative = TRUE,
  check = FALSE
)
```

